FROM php:8.2-apache

# Install ekstensi PHP yang dibutuhkan
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Salin semua file ke dalam container
COPY . /var/www/html/

# Aktifkan rewrite module (CI4 butuh ini)
RUN a2enmod rewrite

# Ubah DocumentRoot ke public/
WORKDIR /var/www/html
RUN sed -i 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/000-default.conf

# Set permission (optional)
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
